# Generated by Django 3.0.5 on 2021-11-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('do_until', models.DateField()),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Done')])),
            ],
            options={
                'ordering': ['do_until', 'status'],
            },
        ),
    ]
